// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-T-R31ZQA4HtK_XShAN5GpnQb3WSCcyI',
    appId: '1:871817647312:web:bf15e830453ec014c1bad5',
    messagingSenderId: '871817647312',
    projectId: 'venuevantage-493511',
    authDomain: 'venuevantage-493511.firebaseapp.com',
    storageBucket: 'venuevantage-493511.firebasestorage.app',
    measurementId: 'G-BW29HNB7YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dj5q4aRkoTVJAdRpcDe-kR_wZYQCLXM',
    appId: '1:871817647312:android:26c219a43709b253c1bad5',
    messagingSenderId: '871817647312',
    projectId: 'venuevantage-493511',
    storageBucket: 'venuevantage-493511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6U-1BuDBuRn7WZNkH_PCGLTShF8RIzTk',
    appId: '1:871817647312:ios:d9026dc7c1e92da4c1bad5',
    messagingSenderId: '871817647312',
    projectId: 'venuevantage-493511',
    storageBucket: 'venuevantage-493511.firebasestorage.app',
    iosBundleId: 'com.example.venueVantage',
  );
}
